# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtNames',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_suite', models.CharField(max_length=200)),
                ('filing_date', models.DateTimeField(default=datetime.datetime(2017, 6, 16, 19, 27, 22, 420000))),
                ('case_no', models.CharField(max_length=50)),
                ('previous_date', models.DateTimeField(default=datetime.datetime(2017, 6, 16, 19, 27, 22, 420000))),
                ('name_of_the_party', models.CharField(max_length=200, null=True)),
                ('appering_for', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('JUDGEMENT', 'Judgement'), ('FAVOUR', 'Favour'), ('NON FAVOUR', 'Non Favour')], max_length=30)),
                ('citation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('remarks', models.CharField(max_length=300)),
                ('court_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.CourtNames')),
            ],
        ),
    ]
