# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNumbers',
            fields=[
                ('case_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CourtNames',
            new_name='AppearingFor',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='appering_for',
            new_name='appearing_for',
        ),
        migrations.RemoveField(
            model_name='events',
            name='case_no',
        ),
        migrations.AlterField(
            model_name='events',
            name='court_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Court'),
        ),
        migrations.AlterField(
            model_name='events',
            name='filing_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='previous_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='stage',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='case_no',
            field=models.ManyToManyField(to='calender.CaseNumbers'),
        ),
    ]
